default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['BB_PASS'] %>

development:
  <<: *default
  database: leforex_develop

test:
  <<: *default
  database: leforex_test

production:
  <<: *default
  database: leforex_production
